package software.angus.sorcery;

public enum Spellbook {
    FIREBALL, SNOWBALL, DRAGONBREATH, WITHER, EGG, LIGHTNING, FORTIFY, HEAL, IMPERFECTION, MEDITATE, EARTHENSHIELD, DETECT, METEOR, RESTORE;
}
